vim.lsp.enable("luals")
vim.lsp.enable("basedpyright")
vim.lsp.enable("ruff")
vim.lsp.enable("gopls")
vim.lsp.enable("cspell")
vim.lsp.enable("clangd")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("vala_ls")
